import React from 'react'

export default function TermsPage() {
    return (
        <main style={{
            minHeight: '100vh',
            background: 'linear-gradient(to bottom, #0f172a, #1e293b)',
            color: '#fff',
            padding: '4rem 2rem',
            fontFamily: "'Inter', sans-serif"
        }}>
            <div style={{ maxWidth: '800px', margin: '0 auto' }}>
                <h1 style={{ fontSize: '3rem', marginBottom: '2rem', color: '#40e0d0' }}>Terms & Conditions</h1>

                <section style={{ marginBottom: '3rem' }}>
                    <h2 style={{ color: '#fbbf24', marginBottom: '1rem' }}>1. Introduction</h2>
                    <p style={{ lineHeight: '1.6', color: '#cbd5e1' }}>
                        Welcome to the AI Adventure Platform. By accessing or playing our game, you agree to be bound by these Terms and Conditions.
                    </p>
                </section>

                <section style={{ marginBottom: '3rem' }}>
                    <h2 style={{ color: '#fbbf24', marginBottom: '1rem' }}>2. AI-Generated Content</h2>
                    <p style={{ lineHeight: '1.6', color: '#cbd5e1' }}>
                        This game uses Artificial Intelligence (AI) to generate storylines, images, and audio.
                        While we strive for quality, AI content may occasionally be unpredictable or contain inaccuracies.
                        We take no responsibility for the fictional scenarios generated by the AI based on user inputs.
                    </p>
                </section>

                <section style={{ marginBottom: '3rem' }}>
                    <h2 style={{ color: '#fbbf24', marginBottom: '1rem' }}>3. User Conduct</h2>
                    <p style={{ lineHeight: '1.6', color: '#cbd5e1' }}>
                        You agree to use this platform responsibly. You must not:
                    </p>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem', color: '#cbd5e1', lineHeight: '1.6' }}>
                        <li>Input hate speech, explicit content, or illegal material into the AI prompts.</li>
                        <li>Attempt to exploit bugs or manipulate the game logic.</li>
                        <li>Harass other players in multiplayer modes.</li>
                    </ul>
                </section>

                <section style={{ marginBottom: '3rem' }}>
                    <h2 style={{ color: '#fbbf24', marginBottom: '1rem' }}>4. Intellectual Property</h2>
                    <p style={{ lineHeight: '1.6', color: '#cbd5e1' }}>
                        The game engine, code, and design are the property of the developers.
                        The stories you create are yours to enjoy, but the platform retains the right to use anonymized gameplay data for improvement.
                    </p>
                </section>

                <section style={{ marginBottom: '3rem' }}>
                    <h2 style={{ color: '#fbbf24', marginBottom: '1rem' }}>5. Disclaimer</h2>
                    <p style={{ lineHeight: '1.6', color: '#cbd5e1' }}>
                        The game is provided "as is" without warranties of any kind.
                        We are not liable for any data loss or interruptions in service.
                    </p>
                </section>

                <p style={{ marginTop: '4rem', fontSize: '0.9rem', color: '#64748b' }}>
                    Last Updated: Feb 2026
                </p>
            </div>
        </main>
    )
}
