-- ==========================================
-- COMPLETE ACTIONABLE HINTS FOR ALL 20 SCENES
-- ==========================================

-- Story 1: Tanaji Malusare
-- =========================

-- Scene 1: The Sting of Purandar
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Acknowledge the weight of this defeat to proceed (e.g., say continue or next)."'::jsonb), '{hi,valid_actions_hint}', '"आगे बढ़ने के लिए इस हार को स्वीकार करें (जैसे, आगे बोलें)।"'::jsonb), '{mr,valid_actions_hint}', '"पुढे जाण्यासाठी हा पराभव मान्य करा (उदा. पुढे सांगा)।"'::jsonb), '{hi-en,valid_actions_hint}', '"Aage badhne ke liye is defeat ko accept karein (jaise, aage boliye)."'::jsonb), '{mr-en,valid_actions_hint}', '"Pudhe janyasathi ya defeat la accept kara (jaise, pudhe sanga)."'::jsonb), valid_paths = '[{"intent_keywords": ["continue", "next", "proceed", "understand", "acknowledge", "accept"], "next_scene_id": "550e8400-e29b-41d4-a716-446655440002", "success_message": "⚔️ The weight of this defeat settles on your shoulders. But you know this is not the end...", "outcome_type": "success"}]'::jsonb WHERE scene_number = 1 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 2: The Mother's Gaze
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Go and meet Rajmata Jijabai in her chambers."'::jsonb), '{hi,valid_actions_hint}', '"राजमाता जीजाबाई से उनके कक्ष में जाकर मिलें।"'::jsonb), '{mr,valid_actions_hint}', '"राजमाता जिजाबाईंच्या कक्षात जाऊन त्यांची भेट घ्या."'::jsonb), '{hi-en,valid_actions_hint}', '"Rajmata Jijabai se unke chamber mein jaakar milrein."'::jsonb), '{mr-en,valid_actions_hint}', '"Rajmata Jijabai chya chamber madhe jaaun tyanchi bhet ghya."'::jsonb), valid_paths = '[{"intent_keywords": ["continue", "next", "proceed", "listen", "approach", "meet"], "next_scene_id": "550e8400-e29b-41d4-a716-446655440003", "success_message": "🏰 You steel yourself for what is to come. The Rajmata''s determination is legendary...", "outcome_type": "success"}]'::jsonb WHERE scene_number = 2 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 3: The Impossible Demand
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"State clearly that you volunteer to lead this mission."'::jsonb), '{hi,valid_actions_hint}', '"स्पष्ट रूप से कहें कि आप इस मिशन का नेतृत्व करने के लिए तैयार हैं।"'::jsonb), '{mr,valid_actions_hint}', '"स्पष्टपणे सांगा की तुम्ही या मोहिमेचे नेतृत्व करण्यास तयार आहात."'::jsonb), '{hi-en,valid_actions_hint}', '"Clear boliye ki aap is mission ko lead karne ke liye ready hain."'::jsonb), '{mr-en,valid_actions_hint}', '"Clear sanga ki tumhi ya mission la lead karnyasathi ready ahat."'::jsonb), valid_paths = '[{"intent_keywords": ["volunteer", "accept", "take mission", "will do", "I will go", "let me", "send me", "yes", "tayyar", "swayamsevak", "main jaunga", "mi janar"], "next_scene_id": "550e8400-e29b-41d4-a716-446655440004", "success_message": "🎖️ Your words hang in the air. The decision is made. You will lead this impossible mission!", "outcome_type": "success"}]'::jsonb WHERE scene_number = 3 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 4: The Wedding Interrupted
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Duty calls. Tell them you must leave for the mission immediately."'::jsonb), '{hi,valid_actions_hint}', '"कर्तव्य पुकार रहा है। कहें कि आपको तुरंत मिशन के लिए निकलना होगा।"'::jsonb), '{mr,valid_actions_hint}', '"कर्तव्य साद घालत आहे. सांगा की तुम्हाला त्वरित मोहिमेसाठी निघावे लागेल."'::jsonb), '{hi-en,valid_actions_hint}', '"Duty bula rahi hai. Boliye ki aapko turant mission ke liye nikalna hoga."'::jsonb), '{mr-en,valid_actions_hint}', '"Duty bolavat ahe. Sanga ki tumhala lagach mission sathi nighave lagel."'::jsonb), valid_paths = '[{"intent_keywords": ["leave", "go", "depart", "ride", "travel", "journey", "duty", "yes", "shaadi chhodo", "farz", "kartavya", "nigha"], "next_scene_id": "550e8400-e29b-41d4-a716-446655440005", "success_message": "🐎 You bid farewell to your family and mount your horse. The road to Raigad awaits.", "outcome_type": "success"}]'::jsonb WHERE scene_number = 4 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 5: The Vow
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Take the sacred vow to win Sinhagad or die trying."'::jsonb), '{hi,valid_actions_hint}', '"सिंहगढ़ जीतने या मर मिटने की पवित्र प्रतिज्ञा लें।"'::jsonb), '{mr,valid_actions_hint}', '"सिंहगड जिंकण्याची किंवा प्राण देण्याची पवित्र शपथ घ्या."'::jsonb), '{hi-en,valid_actions_hint}', '"Sinhagad jeetne ya mar mitne ki pavitra pratigya lein."'::jsonb), '{mr-en,valid_actions_hint}', '"Sinhagad jinknyachi kiva pran denyachi pavitra shapath ghya."'::jsonb), valid_paths = '[{"intent_keywords": ["take vow", "accept", "swear", "promise", "pledge", "sinhagad or death", "yes", "vow", "pratigya", "shapath", "vachan"], "next_scene_id": "550e8400-e29b-41d4-a716-446655440006", "success_message": "🙏 The vow is taken. Your fate is sealed. Now begins the preparation for the impossible mission.", "outcome_type": "success"}]'::jsonb WHERE scene_number = 5 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 6: The Omen at the Cliff
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Command Yashwanti to climb firmly to overcome the bad omen."'::jsonb), '{hi,valid_actions_hint}', '"अपशकुन को दूर करने के लिए यशवंती को मजबूती से चढ़ने का आदेश दें।"'::jsonb), '{mr,valid_actions_hint}', '"अपशकुन दूर करण्यासाठी यशवंतीला ठामपणे चढण्याची आज्ञा द्या."'::jsonb), '{hi-en,valid_actions_hint}', '"Apshakun ko door karne ke liye Yashwanti ko firmly chadhne ka order dein."'::jsonb), '{mr-en,valid_actions_hint}', '"Apshakun dur karnyasathi Yashwantila thampane chadhnyachi adesh dya."'::jsonb) WHERE scene_number = 6 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 7: The Lion's Charge
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"The element of surprise is lost. Give the order to charge and attack!"'::jsonb), '{hi,valid_actions_hint}', '"सरप्राइज खो गया है। हमला करने और धावा बोलने का आदेश दें!"'::jsonb), '{mr,valid_actions_hint}', '"सरप्राईज संपले आहे. हल्ला करण्याचा आणि तुटून पडण्याचा आदेश द्या!"'::jsonb), '{hi-en,valid_actions_hint}', '"Surprise kho gaya hai. Attack karne aur hamla karne ka order dein!"'::jsonb), '{mr-en,valid_actions_hint}', '"Surprise sample ahe. Attack karnyasathi ani halla karnyasathi adesh dya!"'::jsonb) WHERE scene_number = 7 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 8: The Duel
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Continue the duel and fight the commander with all your strength."'::jsonb), '{hi,valid_actions_hint}', '"द्वंद्व जारी रखें और पूरी ताकत से सेनापति से लड़ें।"'::jsonb), '{mr,valid_actions_hint}', '"द्वंद्व चालू ठेवा आणि सर्व शक्तीनिशी सेनापतीशी लढा."'::jsonb), '{hi-en,valid_actions_hint}', '"Duel continue karein aur puri power se commander se ladrein."'::jsonb), '{mr-en,valid_actions_hint}', '"Duel chalu theva ani purn shaktine commander shi ladha."'::jsonb) WHERE scene_number = 8 AND story_id = '550e8400-e29b-41d4-a716-446655440000';

-- Scene 9: Suryaji's Rally
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Support your men and choose to rally them to finish the fight."'::jsonb), '{hi,valid_actions_hint}', '"अपने आदमियों का समर्थन करें और लड़ाई खत्म करने के लिए उन्हें एकजुट करें।"'::jsonb), '{mr,valid_actions_hint}', '"तुमच्या माणसांना साथ द्या आणि लढाई संपवण्यासाठी त्यांना एकत्र करा."'::jsonb), '{hi-en,valid_actions_hint}', '"Apne aadmiu ko support karein aur ladai khatam karne ke liye unhe rally karein."'::jsonb), '{mr-en,valid_actions_hint}', '"Aplya mansanna sath dya ani ladhai sampvanyasathi tyanna ekatra kara."'::jsonb) WHERE scene_number = 9 AND story_id = '550e8400-e29b-41d4-a716-446655440000';


-- Story 2: Baji Prabhu
-- ====================

-- Scene 1: The Calling
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Express your total loyalty to Maharaj and the cause of Swarajya."'::jsonb), '{hi,valid_actions_hint}', '"महाराज और स्वराज्य के प्रति अपनी पूर्ण निष्ठा व्यक्त करें।"'::jsonb), '{mr,valid_actions_hint}', '"महाराज आणि स्वराज्याप्रती तुमची पूर्ण निष्ठा व्यक्त करा."'::jsonb), '{hi-en,valid_actions_hint}', '"Maharaj aur Swarajya ke prati apni full loyalty express karein."'::jsonb), '{mr-en,valid_actions_hint}', '"Maharaj ani Swarajya prati tumchi purn loyalty express kara."'::jsonb) WHERE scene_number = 1 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');

-- Scene 2: The Trap
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Suggest a bold plan to escape the siege of Panhala fort."'::jsonb), '{hi,valid_actions_hint}', '"पन्हाळा किले के घेरे से निकलने की एक साहसिक योजना का सुझाव दें।"'::jsonb), '{mr,valid_actions_hint}', '"पन्हाळा किल्ल्याच्या वेढ्यातून निसटण्यासाठी एका धाडसी योजनेचा सल्ला द्या."'::jsonb), '{hi-en,valid_actions_hint}', '"Panhala fort ke ghere se nikalne ka ek bold plan suggest karein."'::jsonb), '{mr-en,valid_actions_hint}', '"Panhala killya chya vedhyatun nisatnyasathi ek bold plan suggest kara."'::jsonb) WHERE scene_number = 2 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');

-- Scene 3: The Deception
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Decide to support Shiva Nhavi''s brave plan to decoy the enemy."'::jsonb), '{hi,valid_actions_hint}', '"दुश्मन को गुमराह करने के लिए शिवा नावी की वीर योजना का समर्थन करें।"'::jsonb), '{mr,valid_actions_hint}', '"शत्रूला फसवण्यासाठी शिवा न्हावी यांच्या धाडसी योजनेला पाठिंबा द्या."'::jsonb), '{hi-en,valid_actions_hint}', '"Enemy ko distract karne ke liye Shiva Nhavi ke brave plan ko support karein."'::jsonb), '{mr-en,valid_actions_hint}', '"Enemy la distract karnyasathi Shiva Nhavi chya brave plan la support kara."'::jsonb) WHERE scene_number = 3 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');

-- Scene 4: The Sacrifice
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"The decoy is captured. Run now and make sure his sacrifice counts."'::jsonb), '{hi,valid_actions_hint}', '"बहुरूपिया पकड़ा गया। अब भागें और उसका बलिदान सार्थक करें।"'::jsonb), '{mr,valid_actions_hint}', '"बहुरूपिया पकडला गेला. आता धावा आणि त्याचे बलिदान सार्थ करा."'::jsonb), '{hi-en,valid_actions_hint}', '"Decoy pakda gaya. Ab bhago aur uska sacrifice waste mat hone do."'::jsonb), '{mr-en,valid_actions_hint}', '"Decoy pakadla gela. Ata pala ani tyache sacrifice vaya jau deu naka."'::jsonb) WHERE scene_number = 4 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');

-- Scene 5: Race to Ghod Khind
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Ride through the storm and mud at maximum speed without stopping."'::jsonb), '{hi,valid_actions_hint}', '"बिना रुके पूरी रफ्तार से तूफान और कीचड़ के बीच से निकलें।"'::jsonb), '{mr,valid_actions_hint}', '"न थांबता पूर्ण वेगाने वादळ आणि चिखलातून घोडा दौडा."'::jsonb), '{hi-en,valid_actions_hint}', '"Bina ruke full speed se storm aur mud ke beech se nikalein."'::jsonb), '{mr-en,valid_actions_hint}', '"Na thambta full speed ne storm ani chikhalatun ghoda dauda."'::jsonb) WHERE scene_number = 5 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');

-- Scene 6: The Ultimate Volunteer
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Tell Maharaj that you will stay behind to hold the narrow pass."'::jsonb), '{hi,valid_actions_hint}', '"महाराज से कहें कि आप संकरी खिंड में उन्हें रोकने के लिए पीछे रुकेंगे।"'::jsonb), '{mr,valid_actions_hint}', '"महाराजांना सांगा की तुम्ही अरुंद खिंडीत त्यांना रोखण्यासाठी मागे थांबाल."'::jsonb), '{hi-en,valid_actions_hint}', '"Maharaj se boliye ki aap narrow pass mein unhe rokne ke liye peeche rukenge."'::jsonb), '{mr-en,valid_actions_hint}', '"Maharajanna sanga ki tumhi arund khindit tyanna rokhnyasathi mage thambal."'::jsonb) WHERE scene_number = 6 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');

-- Scene 7: The Stand
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Focus on the battle: hold the line and fight every wave of enemies."'::jsonb), '{hi,valid_actions_hint}', '"युद्ध पर ध्यान दें: लाइन को थामे रखें और दुश्मनों की हर लहर से लड़ें।"'::jsonb), '{mr,valid_actions_hint}', '"युद्धावर लक्ष केंद्रित करा: खिंड लढवा आणि शत्रूच्या प्रत्येक लाटेचा प्रतिकार करा."'::jsonb), '{hi-en,valid_actions_hint}', '"War par focus karein: line ko thaame rakhein aur enemies se ladrein."'::jsonb), '{mr-en,valid_actions_hint}', '"War var focus kara: khind ladhva ani enemies shi ladha."'::jsonb) WHERE scene_number = 7 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');

-- Scene 8: Final Push
UPDATE public.scenes SET translations = jsonb_set(jsonb_set(jsonb_set(jsonb_set(jsonb_set(translations, '{en,valid_actions_hint}', '"Endure the pain and keep the enemy at bay until the cannon fires."'::jsonb), '{hi,valid_actions_hint}', '"दर्द सहन करें और तोप चलने तक दुश्मन को रोके रखें।"'::jsonb), '{mr,valid_actions_hint}', '"वेदना सोसा आणि तोफ डागण्यापर्यंत शत्रूला रोखून धरा."'::jsonb), '{hi-en,valid_actions_hint}', '"Pain endure karein aur cannon chalne tak enemy ko roke rakhein."'::jsonb), '{mr-en,valid_actions_hint}', '"Pain endure kara ani cannon danyaparyant enemy la rokhun dhara."'::jsonb) WHERE scene_number = 8 AND story_id = (SELECT id FROM public.stories WHERE title LIKE '%Baji Prabhu%');
